import type { Metadata, Viewport } from "next";
import "./globals.css";
import localFont from "next/font/local";
import BttonWhatsApp from "@/components/BttonWhatsApp";
import Success from "@/components/Success";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"], weight: ["100", "400"] });

const newYork = localFont({
  src: [
    { path: "../../public/font/NewYork.otf", weight: "400", style: "normal" },
  ],
  variable: "--font-newyork",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${newYork.className} font-newyork `}>
        <div className={`${montserrat.className} bg-black`}>
          <Success />
        </div>
        {children}
        <BttonWhatsApp />
      </body>
    </html>
  );
}
